// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
require('dotenv').config();
const { defineConfig } = require("prisma/config");

module.exports = defineConfig({
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
